### ISSUE TITLE
Identify how we can divide our community into teams.

### ISSUE THREAD

**Issue by Abdullahdaeej** [profmasson/IINF.496-596.F2015#10]
I think we missed the first point in our super list. we started our list by how team can effectively communicate.  Let first brainstorm some ideas in how we can divide our community into team. we will put it under item 1 in our super list. 

Note: if anyone need help or have comment in some ideas,  please feel free to raise an issue.

**Comment by massonpj** [comment]
Nice idea, no need to have everyone work on the same problem.

**Comment by rafaelleitao** [comment]
I think that we should pick the main ideas of ours projects and try to make a list or pick the principles shoed and use the items of each group to explain the appliance of the principles in pratice.

**Comment by profmasson** [comment]
There is a real difference between saying what you should do, and doing it. Remember, people respond best to seeing something real, rather than hearing about what might be. Just post what you think is best and ask specific people to review and edit (not comment, EDIT!).

**Comment by profmasson** [comment]
@rafaelleitao I am tasking you with tasking @Cbeni and @ksaroop with doing something to improve the super list. Find a need, nothing too hard or requiring more than 15mins of work, and ask them to do it.
