### ISSUE TITLE
Super List is still waiting your participation!

### ISSUE THREAD

**Issue by Abdullahdaeej** [profmasson/IINF.496-596.F2015#12]
Whenever you got an idea for building our community, just share it in our super list , and match it with its corresponding category.  for the sake of our community, let devote short portion of our time (even 5 -10 min) ever day to think and improve our list. 

@hagyoungbyoun @Cbeni @massonpj @ahussain6 @rafaelleitao @Lauren367 @williams1234 @nmartucci @robzakharchuk66 @ksaroop "Your time will not be wasted if you get involved"

**Comment by nmartucci** [comment]
Hey all, I'm going to do some copy editing later tonight

**Comment by profmasson** [comment]
I am loving all of the participation, let's also make sure we're being "honest," "Mature" and "Humble."

**Comment by nmartucci** [comment]
This list has evolved so much in the past day! Great Job all!

**Comment by profmasson** [comment]
OK, I opened this to highlight how the issues could be used to not only communicate, but specifically put tasks on others or ask someone a specific question. Looks like folks are getting the idea so I am closing this issue.
