### ISSUE TITLE
Did anyone start the H&CF episode for 8 or 9 yet if so where is it at. Lauren

### ISSUE THREAD

**Issue by Lauren367** [profmasson/IINF.496-596.F2015#14]

**Comment by Abdullahdaeej** [comment]
We haven't start the episode yet. let's just start creating two pages for each episode, then whenever anyone is ready they can edit the page.

**Comment by Abdullahdaeej** [comment]
the two pages have been created for each episode.

**Comment by profmasson** [comment]
Great note. Nice to see a question, but better to see a task. I might have said, something like,
"@Abdullahdaeej where is the H&CF episodes 8 & 9?" 
This is a specific answerable question.
You might have also asked a specific task,
"@Abdullahdaeej please create pages for H&CF episodes 8 & 9?" 

Good discussions are direct and result in something that can be directly answered or specifically achieved.

**Comment by Lauren367** [comment]
Thanks been out of town mother's 8 3rd birthday. I am back
