### ISSUE TITLE
Groupme closed by accident sorry all

### ISSUE THREAD

**Issue by Cbeni** [profmasson/IINF.496-596.F2015#17]
we started a groupme, add your numbers so we could get started and be able to communicate easier.

**Comment by rafaelleitao** [comment]
Rafael Oliveira : 518-986-0862

**Comment by ahussain6** [comment]
Aneesa Hussain: 1-518-364-7916

Sent from my iPhone

On Dec 3, 2015, at 5:43 PM, rafaelleitao <notifications@github.com<mailto:notifications@github.com>> wrote:


Rafael Oliveira : 518-986-0862

-

**Comment by nmartucci** [comment]
Nick Martucci:718-440-5427

**Comment by ksaroop** [comment]
Kevin Saroop: 347-301-1779


________________________________

**Comment by Abdullahdaeej** [comment]
Abdullah Aldaeej:  929-256-9733

**Comment by Lauren367** [comment]
Lauren Harris 518-482-8037 home or cell 518-364-8037

**Comment by massonpj** [comment]
@Cbeni You might want to remove these phone numbers as they are in the public!
