### ISSUE TITLE
what code of conduct to be used?

### ISSUE THREAD

**Issue by Lauren367** [profmasson/IINF.496-596.F2015#19]
@Abdullahdaeej @hagyoungbyoun @Cbeni @massonpj @ahussain6 @rafaelleitao @Lauren367 @williams1234 @nmartucci @robzakharchuk66 @ksaroop

**Comment by Lauren367** [comment]
@Cbeni I believe I may have closed issue number 18 in error.

**Comment by Abdullahdaeej** [comment]
Just renamed this issue title. this issue will incorporate our opinion and discussion for the code of conduct.
