### ISSUE TITLE
Incremental dev #1: mission statement

### ISSUE THREAD

**Issue by nmartucci** [profmasson/IINF.496-596.F2015#20]
Lorenzo - what do we want out to do in the present and future??

Nick- Make games an connect the community together through multiplayer activities

**Comment by Abdullahdaeej** [comment]
Abdul- Develop free/open source online games programs that connect people together through multiplayer activities.

**Comment by Lauren367** [comment]
Group that sounds good with Mutiny developing games to be played online that will have people interacting together by way multiplayer activities.

**Comment by Abdullahdaeej** [comment]
Mission statement has been aggregated and posted in the Mutiny project wiki page. you can modify it anytime on that page. so now i will close this issue
