### ISSUE TITLE
Skype vs IRC

### ISSUE THREAD

**Issue by Abdullahdaeej** [profmasson/IINF.496-596.F2015#22]
Skype and IRC perform the same function: real time communication. The different between them is that
IRC is embedded in our community website, whereas Skype  is an external tool.

Do we think we need to choose one of them, if so we need to vote.

Note: use this thread to sharing your though regard this issue.

**Comment by williams1234** [comment]
I would say use the one embedded to the website, IRC!

**Comment by williams1234** [comment]
or we can use both and make Skype a optional feature...

**Comment by Abdullahdaeej** [comment]
Sounds great. in this case, IRC will be used  as the main real-time channel and Skype as an option feature.
