### ISSUE TITLE
Extending: Build an environment conducive to our wider goals

### ISSUE THREAD

**Issue by williams1234** [profmasson/IINF.496-596.F2015#23]
let collaborate to restructure this strategic plan!

**Comment by nmartucci** [comment]
similar to xbox live or psn where there is a chat feature, either being text or voice, having the ability to view other's game library or current game they're playing (like a status)

**Comment by robzakharchuk66** [comment]
Thats a great idea

**Comment by Cbeni** [comment]
this would make communication easier not just games but for whatever you want to talk about. especially if you have a "friends list"

**Comment by nmartucci** [comment]
Exactly and maybe we can have it cross platform?

**Comment by Cbeni** [comment]
yea!! the more inclusive the better!

**Comment by Abdullahdaeej** [comment]
Great. Game development environment should promote informal communication like chats.

**Comment by williams1234** [comment]
Yea especially if we are keep it in line with the show, it was meant to be a game but also a means of interaction and communication for its members!

**Comment by ahussain6** [comment]
I agree! This is a good idea to encourage real-time communication.

**Comment by Lauren367** [comment]
texting during play is also good

**Comment by rafaelleitao** [comment]
i have liked the @nmartucci  idea!, even a simple thing like the possibility to text you friends would be a good idea.
