### ISSUE TITLE
Extending: Define the scope of each team, and help team members understand that scope

### ISSUE THREAD

**Issue by williams1234** [profmasson/IINF.496-596.F2015#24]

**Comment by williams1234** [comment]
So for this, i was think we should look at the different aspect of the company and create teams to help each part function

**Comment by Lauren367** [comment]
to provide more teams so one can be able understand with more breakdowns.

**Comment by williams1234** [comment]
so we will have the gaming part, the communication/interaction, management/admin, creativity and design and finally the base coding/website!

**Comment by ahussain6** [comment]
I think we should list as many teams as we can. This will help us divide them into separate categories and make teams accordingly.

**Comment by Cbeni** [comment]
the more teams we can list, would be better because then we can take multiple teams and then start grouping them together to create a more concise team with sub groups that can lead to a efficient collaboration between everyone?

**Comment by Abdullahdaeej** [comment]
User team scope will be  playing the developed games , collaborate on the game features.

**Comment by Abdullahdaeej** [comment]
Developer team scope will be in the code development , fixing bugs.

**Comment by Abdullahdaeej** [comment]
Graphic designer scope will be in developing interfaces for the games.

**Comment by robzakharchuk66** [comment]
I also think we should list all the different teams we may have. Then delete any teams we don't need and describe the ones we have more in depth.
