### ISSUE TITLE
Who will fund our Mutiny Project?

### ISSUE THREAD

**Issue by ahussain6** [profmasson/IINF.496-596.F2015#25]

**Comment by robzakharchuk66** [comment]
We can present our ideas to investors to get funding.

**Comment by Cbeni** [comment]
we can start with fundraising in the beginning, those who are interested in the project can donate to help it develop and then go from there?

**Comment by Abdullahdaeej** [comment]
Good point!  
The project could be funded by external entities. So in this case, we need a new team ( Admistrative ) to coordinate with external entities for funding, or even other company participations

**Comment by ahussain6** [comment]
Start with donations from original "founders" and then funders come later on.

**Comment by nmartucci** [comment]
Have fund raisers at events and expos and stuff!

**Comment by rafaelleitao** [comment]
We could do the same as the eclipse foundation does raising money by asking donations!
http://www.eclipse.org/donate/

**Comment by Cbeni** [comment]
at our events we could have giveaways, raffles and things like that to draw crowds in and bring in the $$$

**Comment by Abdullahdaeej** [comment]
how about having "steering committee" instead of "Administrative team". this community would consist of co-founders to fund and manage the community.

**Comment by Abdullahdaeej** [comment]
This committee would also nominate or include members from user/developer/graphic teams.

**Comment by Cbeni** [comment]
would that help in emphasizing that we are not trying to stick to a hierarchical style of leadership?   that's what i think of when reading "steering committee". Why do you suggest this @Abdullahdaeej

**Comment by Abdullahdaeej** [comment]
this is no change in the hierarchical. it just re-naming. it has the same function.

**Comment by Abdullahdaeej** [comment]
so in this case we do not need to adjust the first strategic plan , and include new teams. same thing would be for the QA committee instead of team.

**Comment by Abdullahdaeej** [comment]
ok never mind; that might confuse between team and committee. let back to our original hierarchical style of leadership.

**Comment by rafaelleitao** [comment]
I think that Instead worry about the name, we should focus in how it will work because the name is does not influence in how the members interact and work. Let stay with original and add more groups when necessary!

**Comment by williams1234** [comment]
we could invest our personal capital initially to be used as seed money, to get the company off the ground and running.
