### ISSUE TITLE
hi all code of conduct posted to google doc  I think we need to add some staments or change the one presented letme know what you guys think.

### ISSUE THREAD

**Issue by Lauren367** [profmasson/IINF.496-596.F2015#28]

**Comment by Abdullahdaeej** [comment]
Thanks @Lauren367  that code of conduct looks awesome.  I include also one more point (When we disagree, we consult others.) which adopted from OpenStack code of conduct. This point explain how the community should act in case of disagreement. 

Check the google doc, last point in the code of conduct.

**Comment by Lauren367** [comment]
@Abdullahdaeej I will check that out also to we have provide the creative commons license statement giving us rights or just provide the link of the sites used for code of conduct?????

**Comment by Abdullahdaeej** [comment]
@Lauren367  we will list the items and also provide the link of the sites for references.
