### ISSUE TITLE
Roles and Responsibilities

### ISSUE THREAD

**Issue by hagyoungbyoun** [profmasson/IINF.496-596.F2015#29]
Hi guys,
For the section 'Roles and Responsibilities', are we supposed to specify individual job of each position in the teams? or does it mean the roles of the community as a whole?

**Comment by Abdullahdaeej** [comment]
I think we need to specify the main job positions on the community, like "committer" "QA" "Admin" etc

**Comment by rafaelleitao** [comment]
I think we should just specify the role to be performed by the member.for example java programmer , tester, marketing especialist or something like that!

**Comment by ksaroop** [comment]
I agree with Rafael. I think we should break down the roles and responsibilities of each member of each team. In that sense, it will be more thorough and detailed when people read it. I can write some of that information if someone else wants to add to or review it.

**Comment by nmartucci** [comment]
I feel the same however the roles could be more broad than specific

**Comment by ahussain6** [comment]
I personally think roles should be more broad than specific so it leaves it more to the user to choose what exactly they want to do.

On Dec 15, 2015, at 11:44 AM, nmartucci <notifications@github.com<mailto:notifications@github.com>> wrote:

I feel the same however the roles could be more broad than specific

##

**Comment by ksaroop** [comment]
If we want the roles to be broad, should we then set requirements for the position so at least members would know what is expected of them to know before they join the team. For instance, programmers should have a knowledge of C++, java, etc. so that we can guide people with those interests to those teams.

**Comment by Cbeni** [comment]
Good point @ahussain6 

i agree with @ksaroop , there should definitely be requirements for positions. its just like the first day of class when we  were asked where we fell on the chart; whether we were contributors, creators, etc and how heavily we were involved in open source material. So if people know what is needed to get a job done, they can provide their skills most efficiently on the correct team.

**Comment by Abdullahdaeej** [comment]
I totally agree with you; but we should do it in different way than just explaining the teams (which already well explained in other sections). 

I look at the role and responsibility section, it looks perfect. it well specify the role & responsibility under each team.
